### ISSUE TITLE
Fail to yarn start:networks

### ISSUE THREAD

**Issue by Troublor** [Giveth/feathers-giveth#148]
Got an error when run `yarn start:networks`:

```
$ node scripts/startBridge.js
internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module './build/Release/scrypt'
Require stack:
- /home/troublor/workspace/giveth/feathers-giveth/node_modules/scrypt/index.js
- /home/troublor/workspace/giveth/feathers-giveth/node_modules/scrypt.js/node.js
- /home/troublor/workspace/giveth/feathers-giveth/node_modules/web3-eth/node_modules/web3-eth-accounts/src/index.js
- /home/troublor/workspace/giveth/feathers-giveth/node_modules/web3-eth/src/index.js
- /home/troublor/workspace/giveth/feathers-giveth/node_modules/giveth-bridge/node_modules/web3/src/index.js
- /home/troublor/workspace/giveth/feathers-giveth/node_modules/giveth-bridge/lib/Relayer.js
- /home/troublor/workspace/giveth/feathers-giveth/node_modules/giveth-bridge/lib/bridge.js
- /home/troublor/workspace/giveth/feathers-giveth/node_modules/giveth-bridge/bridge.js
- /home/troublor/workspace/giveth/feathers-giveth/scripts/startBridge.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/troublor/workspace/giveth/feathers-giveth/node_modules/scrypt/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/troublor/workspace/giveth/feathers-giveth/node_modules/scrypt/index.js',
    '/home/troublor/workspace/giveth/feathers-giveth/node_modules/scrypt.js/node.js',
    '/home/troublor/workspace/giveth/feathers-giveth/node_modules/web3-eth/node_modules/web3-eth-accounts/src/index.js',
    '/home/troublor/workspace/giveth/feathers-giveth/node_modules/web3-eth/src/index.js',
    '/home/troublor/workspace/giveth/feathers-giveth/node_modules/giveth-bridge/node_modules/web3/src/index.js',
    '/home/troublor/workspace/giveth/feathers-giveth/node_modules/giveth-bridge/lib/Relayer.js',
    '/home/troublor/workspace/giveth/feathers-giveth/node_modules/giveth-bridge/lib/bridge.js',
    '/home/troublor/workspace/giveth/feathers-giveth/node_modules/giveth-bridge/bridge.js',
    '/home/troublor/workspace/giveth/feathers-giveth/scripts/startBridge.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by Troublor** [comment]
`npm install `succeeded before with
```
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@3.0.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-cli@2.1.5 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN feathers-giveth@0.0.0 No repository field.
npm WARN feathers-giveth@0.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 364808 packages in 5.733s
found 208 vulnerabilities (59 low, 6 moderate, 135 high, 8 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by Troublor** [comment]
Solved by changing `require("./build/Release/scrypt")` to `require("scrypt")` in `/node_modules/scrypt/index.js`, though I could understand the root cause. 
This problem is a bit annoying.
