### ISSUE TITLE
When creating a campaign I get an _addMilestone error

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#35]
Reproduce:

1. create a campaign

Now check the feathers console

```
_addMilestone error -> Error: Returned error: Error: VM Exception while executing eth_call: invalid opcode
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:65907:17
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:85139:5
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:4783:9
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:1343:16
    at replenish (/Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:1863:25)
    at iterateeCallback (/Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:1853:17)
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:1828:16
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:4780:13
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:85135:9
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:81420:7
    at Object.ErrorResponse (/Users/satya/Development/feathers-giveth/node_modules/web3/packages/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/Users/satya/Development/feathers-giveth/node_modules/web3/packages/web3-core-requestmanager/src/index.js:137:36)
    at /Users/satya/Development/feathers-giveth/node_modules/web3/packages/web3-providers-ws/src/index.js:76:44
    at Array.forEach (native)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/Users/satya/Development/feathers-giveth/node_modules/web3/packages/web3-providers-ws/src/index.js:53:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/satya/Development/feathers-giveth/node_modules/web3/packages/web3-providers-ws/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/satya/Development/feathers-giveth/node_modules/web3/packages/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/satya/Development/feathers-giveth/node_modules/web3/packages/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:115:13)
    at WebSocketConnection.emit (events.js:210:7)
    at WebSocketConnection.processFrame (/Users/satya/Development/feathers-giveth/node_modules/web3/packages/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /Users/satya/Development/feathers-giveth/node_modules/web3/packages/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by perissology** [comment]
should be fixed
