### ISSUE TITLE
Processing ProjectAdded` getting fail for a trace

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/feathers-giveth#565]
https://trace.giveth.io/trace/amin-givether-pan-distribution

This is the log for this event:

‍‍```
Trace title is repetitive. Please select a different title for the trace. {"type":"FeathersError","name":"Forbidden","code":403,"className":"forbidden","errors":{},"stack":"Forbidden: Trace title is repetitive. Please select a different title for the trace.\n    at new Forbidden (/home/deploy/feathers-giveth-beta/node_modules/@feathersjs/errors/lib/index.js:107:17)\n    at Object.<anonymous> (/home/deploy/feathers-giveth-beta/src/services/traces/checkTraceName.js:28:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","timestamp":"2021-07-26T14:49:06.491Z”
```

maybe related to #498

**Comment by mohammadranjbarz** [comment]
it fails because title of 
https://trace.giveth.io/trace/ramin-givether-pan-distribution
includes this trace title
