### ISSUE TITLE
Cannot create a new campaign, throws on eth_estimateGas

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#60]
```
"Error: VM Exception while executing eth_estimateGas: invalid opcode
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:65907:17
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:85139:5
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:4783:9
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:1343:16
    at replenish (/Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:1863:25)
    at iterateeCallback (/Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:1853:17)
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:1828:16
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:4780:13
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:85135:9
    at /Users/satya/Development/feathers-giveth/node_modules/ethereumjs-testrpc/build/cli.node.js:81420:7"
```

**Comment by perissology** [comment]
I'm closing, as I'm pretty sure this was an env issue.

feel free to re-open if this is still a bug
